/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main.bankingOperation;

/**
 *
 * @author sagarverma
 */
public class Banking extends javax.swing.JFrame {

    /**
     * Creates new form Banking
     */
    public Banking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAcountCreation = new javax.swing.JMenuItem();
        menuTransaction = new javax.swing.JMenuItem();
        menuStatement = new javax.swing.JMenuItem();
        menuDelectAcoount = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SBI- Banking");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/main/image/MainIcon.jpeg"))); // NOI18N

        jMenu1.setText("File");

        menuAcountCreation.setText("Create Account");
        menuAcountCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcountCreationActionPerformed(evt);
            }
        });
        jMenu1.add(menuAcountCreation);

        menuTransaction.setText("Transaction");
        menuTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionActionPerformed(evt);
            }
        });
        jMenu1.add(menuTransaction);

        menuStatement.setText("Statement");
        menuStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStatementActionPerformed(evt);
            }
        });
        jMenu1.add(menuStatement);

        menuDelectAcoount.setText("DelectAccount");
        menuDelectAcoount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelectAcoountActionPerformed(evt);
            }
        });
        jMenu1.add(menuDelectAcoount);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAcountCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcountCreationActionPerformed
        // TODO add your handling code here:
        new AccountCreation().setVisible(true);
    }//GEN-LAST:event_menuAcountCreationActionPerformed

    private void menuStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStatementActionPerformed
        // TODO add your handling code here:
        new AccountStatement().setVisible(true);
    }//GEN-LAST:event_menuStatementActionPerformed

    private void menuTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionActionPerformed
        // TODO add your handling code here:
        new Transaction().setVisible(true);
    }//GEN-LAST:event_menuTransactionActionPerformed

    private void menuDelectAcoountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelectAcoountActionPerformed
        // TODO add your handling code here:
        new AccountDelete(). setVisible(true);
    }//GEN-LAST:event_menuDelectAcoountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAcountCreation;
    private javax.swing.JMenuItem menuDelectAcoount;
    private javax.swing.JMenuItem menuStatement;
    private javax.swing.JMenuItem menuTransaction;
    // End of variables declaration//GEN-END:variables
}
